### ISSUE TITLE
TX-to-RX spectral display artifact (aka "noise burst") [BUG]

### ISSUE THREAD

**Issue by w-u-2-o** [ramdor/Thetis#204]
**Describe the bug**

FFT latency, along with any display averaging that might be used, causes the spectral display data to lag the actual state of the radio. Thus it seems that there is still a transmission going on even after the radio has switched to receive although this is certainly not true. Add to this the large difference in strength (amplitude) in the sample of the transmitted signal, and changes in the vertical (amplitude) scale between TX and RX, and all together that can create quite a large artifact on the display that looks an awful lot like a noise burst.

**To Reproduce**

- DUP mode must be on (this only occurs in DUP mode).
- Make a transmission.
- Observe the display artifact.

To really exaggerate it, use a high sample rate, e.g. 768KHz, a small FFT size, e.g. 2.93Hz, and turn on spectral display averaging.

**Expected behaviour**

No display artifacts that look like noise bursts on TX-to-RX transitions.

To achieve this the software would need to blank or suppress the FFT data stream from the time transmit RF starts or ends for a duration equal to the FFT length. That way the old data can all go into the bit bucket and be replaced by the data applicable to the current state of the radio. Also, display averaging needs to be reset at the end of the blanking period.

**Desktop (please complete the following information):**

 - Not relevant, this is an internal Thetis issue.

**Additional context**

This problem is only apparent in DUP mode. The spectral display runs continuously in this mode, processing the data from RX1 during both receive and transmit without pause. The FFT settings during both receive and transmit are those set in Setup > Display > RX1.

The FFT settings in Setup > Display > TX are NOT used when in DUP mode (the display scaling settings are).

The only thing that changes on the spectral display between TX and RX states are the scaling and formatting of the display. The RX1 data stream remains constant from the FFT, again without pause between TX and RX states.

FFT calculations are not instantaneous. To work they need to gather blocks of data. Thus the output of the FFT is delayed by the number of samples, or "points", used in the FFT calculation. The calculation is straightforward:

Number of samples = sample rate / frequency resolution

This delay can get quite long. For instance, at 768KHz sample rate and 2.93Hz resolution (aka bin size), that works out to an FFT size, or "length", of 768000/2.93 = 262116 samples. In actuality the size of the FFT wants to be a power of 2 and the closest length to that is 262144, but you get the idea. And since every sample is 1/768000 seconds long, do the math and you get a delay through the FFT of 262144/768000 = 0.341 seconds or 341 milliseconds. That's a pretty long time!

If you add display averaging into this problem space the issue just gets worse.

This problem also occurs in the RX-to-TX direction. It's usually overlooked because the difference in display scaling that most people set up does a good job of masking the issue. For instance, if the panadapter scale is looking down to -130 during RX, but only -70 during TX, then not much is going to be seen. However, if you go through an exercise of making the TX panadapter scaling the same as RX the problem is plainly evident.

**Comment by ramdor** [comment]
this is somewhat improved in the dev branch, and will be available when [2.10.2.3] releases at some point.

**Comment by mdblack98** [comment]
Did you add an option somewhere?  I'm running the latest git pull and don't see much difference.  The Rx->Tx is responding pretty well but Tx->Rx is notably slower than Rx->Tx.

**Comment by ramdor** [comment]
there are two options in the dev branch. The wdsp one does a complete reset to the WDSP buffers. The other option clears only the display DX buffers and delays waterfall agc by the estimated fill time calculated from Scotts notes above. You can have both on, or the DX only, but the wdsp option will require the DX clear.

![image](https://github.com/ramdor/Thetis/assets/3124967/790ea1cf-2aa1-4bb6-b062-91442c921c04)

**Comment by w-u-2-o** [comment]
As Richie says, the math is pretty straightforward. However, Richie had to
add some additional delay to handle the display artifact that was coming
from the waterfall AGC on the TX-to-RX transition, so that can never be
less than 200ms.

I'm still not clear on why there are two separate selectable options
instead of one.

Also, there is still the question of whether it should be enabled for CW
op's.

Thanks,

Scott

**Comment by ramdor** [comment]
> I'm still not clear on why there are two separate selectable options
instead of one.

They do very different things. Some people might want to see fft bins recovering so would have the wdsp option off and the dx one on. The agc delay with the dx clear option covers 99% of waterfall issues which is the setting I use. The the WDSP clear is 100% going to ensure that you wont be seeing old data from the old mox state, and you see this reflected in the panadapter with the instant clear. However the recovery time doesn't feel as intuitive to me on slow sample rates and max size ffts. If user is CW op then if they want old method, just switch the options off as it then behaves as it used to.

https://youtu.be/SEdIuTD2iAw?si=Meuee2SUmjyBDykL

**Comment by ramdor** [comment]
also, the 200ms thing was just something to give the waterfall agc some minimum time to settle. This could probably be based off frame rate/waterfall update time interval. This could be looked at in future but for now I call it done ;)

**Comment by ramdor** [comment]
https://github.com/ramdor/Thetis/issues/235#issuecomment-1790248960

I knew I should have left that option in @w-u-2-o   :)

**Comment by RdWing** [comment]
<Edit/Repost: Well, ramdor reposted it for me, thanks. But here's the text in case. And some thoughts as to why its important for the waterfall to show the truest data it can.>


Hmm, I appreciate that for some users there is a large artifact. I have always worked around it with timing adjustments under Options 1, just a few ms of delay. The new changes, however, seem to cut off the beginning and tail end of the transmission on the waterfall, even though the little burst is still there and being transmitted. We just can't see it now.

It was very comforting knowing that what I saw on the panadapter and waterfall was true to life showing the signal as transmitted...and I'm somehow less comfortable now that it's gone.

Perhaps there is a middle ground that can be achieved? Or can this agc constant be tuned by the user?

I'm also a little concerned because previously you could pretty quickly see if something was being hotswitched, due to it appearing on the panafall, but now it's just dark.

New Version (Remote Kiwi receiver on left showing signal as received, Thetis on Right) 
![Screenshot 2023-11-02 005842](https://github.com/ramdor/Thetis/assets/19214916/36afe77e-5a00-4cd1-9b91-d4b3ab232c1a)
Old Version 
![Screenshot 2023-11-02 010210](https://github.com/ramdor/Thetis/assets/19214916/0032e156-6b9d-4d43-89a9-c1c905615c3c)

**Comment by RdWing** [comment]
For what its worth, 768KHz, a small FFT size, e.g. 2.93Hz, and spectral display averaging on is exactly how I run my 7000 here. 

I really want to differentiate between the blowout seen on the waterfall when unkeying when delays are set to 0, versus the normal end of transmission blip that is actually transmitted over the air.

![Screenshot 2023-11-02 022021](https://github.com/ramdor/Thetis/assets/19214916/505d8273-cfc2-4d74-8347-66803c737422)

I found that you can ameliorate the entire issue altogether by merely setting the MOX delay to a value of around 5 or 6. That should fix it across all bands, at least it does on the 7000 Mk2.5 I have here. Tested it after setting all other RX delay and PTT Hang to 0.

**Comment by w-u-2-o** [comment]
@RdWing -- first off, the waterfall is showing the "truest" data. In this mode you are simply not seeing the junk data that is leftover in the FFT pipeline. See this topic: https://community.apache-labs.com/viewtopic.php?f=9&t=4382&p=22287

@ramdor -- as previously suggested, the DX option (which is now removed) and the WDSP option (in the build) should be tied at the hip. Both on or both off. No need to split the two options out. Call the combined option "Blank old FFT data on spectral display". This way the effect can be optioned off by those who want to see the nasty display artifact or by QSK CW users.

73,

Scott

**Comment by RdWing** [comment]
@w-u-2-o It's a little more nuanced than that. Can we agree that adjusting the MOX delay resolves the blowout issue? Do you not want a true representation of what's being transmitted? I do. 

The new changes are definitely cutting off display of signal start and signal end.  Should the fix to the blowouts be to cutoff the beginning and end display in the waterfall, or just adjust the mox delay. I think #2.

I tested with a signal generator applied to the RX bypass, and keying/unkeying. New thetis has some time when it cuts out. Old thetis shows small amount of leftovers, but also doesn't have the cutouts in question.

Perhaps it's possible to just adjust the waterfall AGC at the tail end to try and match whatever it is during the T->R transition so that both ends appear with the same amplitude.

Re: The WDSP option, I find it slows down the panadapter even longer.

New ![Screenshot 2023-11-02 112950](https://github.com/ramdor/Thetis/assets/19214916/2f6734fa-ccf5-45aa-b85f-16680b95db16)
Old ![Screenshot 2023-11-02 113134](https://github.com/ramdor/Thetis/assets/19214916/2bdbbaf3-915b-4c9e-84e1-50e035795975)

**Comment by RdWing** [comment]
Keying the external signal generator on and off you see a similar type of display, which matches what used to be seen from Thetis transmissions. I think artificially suppressing that is contrary to the intended function of the waterfall display.
![Screenshot 2023-11-02 114755](https://github.com/ramdor/Thetis/assets/19214916/99473915-3908-4a2f-b6ee-4c612ddd3be5)

**Comment by w-u-2-o** [comment]
> @w-u-2-o It's a little more nuanced than that.

Maybe. Maybe not. The problem is while it may be a "truer representation" it becomes impossible to appreciate because the scaling change distorts the presentation of the data badly.

> Can we agree that adjusting the MOX delay resolves the blowout issue?

Again, yes and no. If you are willing to accept the required delay and totally destroy TX-to-RX changeover time, making it 100's of milliseconds long, yes. If you are not willing to accept that (and I'm not), then the answer is no. Remember that many of us run high sample rates with small FFT bin widths. The math is shown above, and MOX delays must be made very large in such cases.

> Do you not want a true representation of what's being transmitted? I do.

That's a fair question. I do. If Richie makes it an option as I suggested above (and what I thought was going to be in the release) then one can pick and choose what they want to see. If it was an option would you have voiced your concerns?

However and however again, upon rethinking this issue, perhaps there is an even better way to fix this problem and achieve a "truer representation". And that way would be to synchronize the change in display scaling (TX-to-RX and RX-to-TX) such that it occurs more properly at the boundary between the last TX sample and the first RX sample, and in the other direction at the boundary between the last RX sample and the first TX sample.

Even if that was achievable (and I'm not sure it is easily done--@ramdor ?), there will still be the problem of a potential for a minor glitch to be visible, and a blanking time associated with waterfall AGC to prevent that from display an ugly glitch. 

This method would provide more accurate results, however is the juice worth the squeeze? I can't make heads or tails of the distorted data that occurs due to the improper scaling or AGC action. It sounds from your comments that you feel there is value there. If it becomes an option then IMHO problem solved, best of both worlds for all.

73,

Scott

**Comment by RdWing** [comment]
> @w-u-2-o 
> Again, yes and no. If you are willing to accept the required delay and totally destroy TX-to-RX changeover time, making it 100's of milliseconds long, yes. If you are not willing to accept that (and I'm not), then the answer is no. Remember that many of us run high sample rates with small FFT bin widths. The math is shown above, and MOX delays must be made very large in such cases.

Maybe your system works differently from mine. At 768k/2.93Hz, the problem stops with a relatively short MOX delay, roughly 10 ms, not 100+. I also try to make sure I stop talking before I unkey which seems to help.

> If it was an option would you have voiced your concerns?

Probably, only because I don't think the tradeoff is worth it. Clipping both ends to hide the anomaly. As someone that sets up and touches a ton of Thetis compatible radios regularly, I don't think this new behavior adds value. So if there's an option, great. But Thetis defaults have long been a source of difficulty and I'm just not sure which way is better.

> ...synchronize the change in display scaling (TX-to-RX and RX-to-TX) such that it occurs more properly at the boundary between the last TX sample and the first RX sample, and in the other direction at the boundary between the last RX sample and the first TX sample.

I think this sounds like a good idea. 

I believe there are two-ish things at play in this issue. 
#1 The first being the blown out display that is seen via TUN (only) when the MOX delay is too short. That's the wide bright line that goes basically all the way horizontally across the waterfall upon TX -> RX transition. This is fixed, for me, by setting the MOX delay to 10.

#2 Even when the MOX delay is set to 10, you can tell there is an amplitude difference between the key down and key up points, even though the power level is the same.

#2.5 Related to that, when transitioning T -> R, after you unassert MOX or TUN, this is when the display scaling plays in. One can see that after T->R is commanded, the spectral information is still shown on the panadapter for some time, even without averaging. Plus, the FFT length. And since the waterfall follows the Spectrum min/max, it blows out. This seems to affect voice i.e. MOX more substantially than it does other modes.

**Comment by ramdor** [comment]
Certainly from the use of GetPixels it is a stream that is constantly being processed by the analyzer threads, and the display engine grabs the data every frame 60fps or whatever is configured.

As it stands the checkbox option to clear WDSP buffers does just that, resets everything display related in the analyser, and GetPixels will return 'not ready' whilst it is refilling/averaging etc and that time is entirely dependant on fft size and sample rate. This is a complete blanking of the data. At the moment, the waterfall agc is frozen for the same delay.

There are two options imo.

1) One where WDSP buffers are cleared. This is like a hard reset. People who are used to seeing the spectrum 'fade' away, or slew back into view on the T/R transition will not like this option, as everything will just vanish. Auto noise floor calcs are paused when this happens as well, because as you notice the spectrum will bottom out.

and

2) An option to delay the waterfall agc after a T/R, and this should be based on the fft size vs sample rate delay *with* some +- config option to adjust/tweak that delay. This adjustable value could be used to wind back the delay to match your burst of RF monitored on another device/websdr/whatever.

Now, in the case of 1) if the data bottoms out as it would, then unless the waterfall agc is frozen it will increase gain to view the low levels of data that are rebuilding from the analyzer. If the analyzer rebuilds much faster than the display rate, then the water fall agc will over compensate and give a blow out horizontal line. This is why potentially 1) and 2) should be combined if 1) is in use.

However, it is quite possible to just use option 2) without option 1). This would allow the 'slow' slew of spectral data and prevent blow out in the waterfall.

Personally, with the settings I run of 384k sample rate, and a 5.859Hz bin, I would only use option 2 as everything clears out fast enough for me. I would then tweak the +- to give me the desired results for the fft/sr in use.

**Comment by w-u-2-o** [comment]
Again, in the current approach the option should be composed of both (1) and (2) together, or nothing.

To put this more simply, from a top down design perspective, and in terms of "a true AND _correct_" presentation:

- RX data should never be presented with TX scaling factors

- TX data should never be presented with RX scaling factors

To do so might be "true", but it is definitely not _correct!_

This can be accomplished two ways:

1. The current blanking scheme (but with the two options either both explicitly exposed to the user or combined in to a single option)

2. Synchronizing the scaling change to match when the continuous data stream changes exactly (this is probably the more "true and correct" method).

The only gotcha in both cases is handling display averaging. If averaging is reset at the transition point and allowed to build back up that ought not to cause too ugly a display artifact.

Thanks,

Scott

**Comment by ramdor** [comment]
edit: helps i put this in the correct issue, thanks Scott.

I  have changed this, to ignore waterfall pixels during the fft fill time. Blank single pixel rows are added instead. I will make a video in due course to highlight things I have discovered. I can also confirm that on my 7000dle2 there is a pulse of rf which can be seen on an external SDR and is now shown in this waterfall change IF rf delay is enough to push it beyond the fft fill time.

**Comment by ramdor** [comment]
Some more testing

https://youtu.be/WEJaRr-9yHo?si=Wz-2T7jC9saDzVZW

**Comment by mdblack98** [comment]
WSJT-X avoids spiking the rigs by applying a ramp to about 12ms of the audio at start and end.Like this (FORTRAN)
! Apply envelope shaping to the first and last symbols  nramp=nint(nsps/8.0)  if(icmplx.eq.0) then     wave(1:nramp)=wave(1:nramp) *                                          &          (1.0-cos(twopi*(/(i,i=0,nramp-1)/)/(2.0*nramp)))/2.0     k1=nsym*nsps-nramp+1     wave(k1:k1+nramp-1)=wave(k1:k1+nramp-1) *                              &          (1.0+cos(twopi*(/(i,i=0,nramp-1)/)/(2.0*nramp)))/2.0  else     cwave(1:nramp)=cwave(1:nramp) *                                        &          (1.0-cos(twopi*(/(i,i=0,nramp-1)/)/(2.0*nramp)))/2.0     k1=nsym*nsps-nramp+1     cwave(k1:k1+nramp-1)=cwave(k1:k1+nramp-1) *                            &          (1.0+cos(twopi*(/(i,i=0,nramp-1)/)/(2.0*nramp)))/2.0  endif
Here's a WAV file you can use to see how it behaves.






Mike W9MDB



 
 
 On Sunday, November 5, 2023 at 10:27:04 PM CST, Richie ***@***.***> wrote: 







Some more testing

https://youtu.be/WEJaRr-9yHo?si=Wz-2T7jC9saDzVZW

**Comment by RdWing** [comment]
Watched the video. I have seen this for a long time. I ran the same test here with a flex 6400, 7000 dle2.5 and hl2, and they all behave the same. For more fun, MOX the radio with the transmit signal generator set to silence, then change to Tone say at 600 Hz, then to silence. I suspect it might have to do with the rise time of the waveform, and I'm not sure if it can or should be fixed. However, adjustable rise time might be a nice thing to have in general. Probably warren will have something to say about that.

_However_, and more importantly, it does confirm the presence of the keying and unkeying artifacts (which should be visible in some form or another). I think what @w-u-2-o was proposing...
 > @w-u-2-o 
> ...synchronize the change in display scaling (TX-to-RX and RX-to-TX) such that it occurs more properly at the boundary between the last TX sample and the first RX sample, and in the other direction at the boundary between the last RX sample and the first TX sample.

...is to not hide them, but to configure Thetis such that the moment MOX occurs, change the waterfall scaling to match the spec min/max, and then to hold that until the T ->R transition completes. That way the color palette doesn't appear totally blown out. I appreciate this is a very simplified take and probably isn't that helpful.

Here's the flex keying and unkeying, just for reference. Even though flex doesn't have DUP, they attempt to show the TX in the waterfall anyways, and we can see it too suffers from a similar display.
![Screenshot 2023-11-05 215130](https://github.com/ramdor/Thetis/assets/19214916/18f791c4-eb12-4136-bdc5-3732f9b953aa)

**Comment by RdWing** [comment]
Maybe related, maybe not. On the left is the Flex cw keying sideband, on the right is the Anan cw keying sideband. On the Anan it changes between TUN and CW, so I suspect the rise time is controlled in CW and not in TUN.
![Screenshot 2023-11-05 232820](https://github.com/ramdor/Thetis/assets/19214916/589df415-7a4d-4f33-8782-088f7ed68191)

**Comment by w-u-2-o** [comment]
Hi Scott and All,

I was first introduced to this discussion late last evening; so, I may not have absorbed all the subject matter yet.  In any case, I will attempt to make a few points:

  *   For data streams coming into any channel of WDSP (for example the TX channel), slew-up and slew-down is provided.  The slew times are adjustable and, in the ChannelMaster, they are currently set to 10ms.  I’d have to check … the console may be resetting those at times, perhaps by mode … not sure.
  *   For carriers generated within WDSP, e.g., AM, FM, Tune, etc., there is additionally an up-slew and the wdsp channel provides the normal down-slew.  The upslew-time is currently set to a fixed value of 5ms but can be made adjustable.  5ms is an acceptable time for a CW edge and does not consume excessive bandwidth.
  *   All slews are along a raised-cosine curve which is about as good as you can do to minimize bandwidth.  There are other shapes possible; however, most take notably more bandwidth and some just change the profile a bit.
  *   If settings like RF Delay, MOX Delay, etc., change the situation, then we should be sure that there’s no hot-switching of relays happening as some of these settings relate to hardware changeover times.  I’d have to review what setting does what … it’s been a while and the names were always a bit confusing to me.
  *   Attempting to sample-synchronize some display scaling change with a TX-RX transition is very likely not practical.  My guess is that if you can get within a hundred or so ms, you’ve done extremely well.  This all depends upon a lot of factors, including FFT_size, etc.  I’ve never tried this; that’s just my initial impression.
  *   The only way to really know what’s happening with these signals is to look at them in the time-domain, as if on an oscilloscope.  As has been discussed, any technique looking at the frequency domain involves a segment of time, not an instant.  We can do time-domain observation of signals in the software with software tools.  However, the final word on this would be to look at the RF output with an actual oscilloscope – this would reveal any hot-switching, etc.

Those are my thoughts for the moment.

73,
Warren  NR0V

**Comment by ramdor** [comment]
closing this off as there is nothing more I can do. Please test out 2.10.3.4 latest pre-release.

Waterfall agc is prevented for period of the fft fill. If a bright noise pulse is shown then it is because the GetPixels data from WDSP is returning that pulse. Use 'purge wdsp display' option if you want that data cleared out.

Note: slews have not been adjusted as part of this.
