### ISSUE TITLE
Unknown option /arch:SSE2

### ISSUE THREAD

**Issue by mdblack98** [ramdor/Thetis#225]
Visual Studio 2022 
Severity	Code	Description	Project	File	Line	Suppression State
Warning	D9002	ignoring unknown option '/arch:SSE2'	wdsp	C:\Users\mdbla\Dropbox\Projects\Thetis\Project Files\Source\wdsp\cl	1	

Perhaps start using Advanced Vector Extensions 2 (X86/X64) (/arch:AVX2) ?

**Comment by ramdor** [comment]
the warning can be ignored, it is just so that we can build as x86 if we need it, but x64 it gets turned on anyway so becomes an unknown option warning afaik

ref the avx2 etc. Have you done any testing to see if there are any tangible improvements in Thetis when compiled with this switched over? What are the implications if it is compiled with that support and the cpu is old and doesn't support them. Would we need to code around this eventuality?

**Comment by mdblack98** [comment]
I was looking for some references on this and there is supposed to be fallback code -- although it seems there were problems with it.The improvement would be with CPU usage by using more efficient code extensions so would take some iterating and tracking of CPU usage to see if there are any notable improvements.
I have a problem building all this stuff now with the nullable references so my testing is limited.

 

    On Saturday, October 21, 2023 at 11:56:58 AM CDT, Richie ***@***.***> wrote:  
 
 


the warning can be ignored, it is just so that we can build as x86 if we need it, but x64 it gets turned on anyway so becomes an unknown option warning afaik

ref the avx2 etc. Have you done any testing to see if there are any tangible improvements in Thetis when compiled with this switched over? What are the implications if it is compiled with that support and the cpu is old and doesn't support them. Would we need to code around this eventuality?

**Comment by ramdor** [comment]
Unless we re-write a bunch of stuff to make use of vectorisation in the c libs, there will be nothing to gain. We would also have to add code to handle the vectored version of a given function/call determined by cpu. Can't see that happening somehow, so closing this.
