### ISSUE TITLE
Burst of waterfall noise after each TX->RX transition. 

### ISSUE THREAD

**Issue by W2PA** [ramdor/Thetis#235]
I believe there is a new bug that cropped up in 2.10.3, the version from last weekend (I know it's not yet a "release").  I pulled the changes Sunday morning and recompiled.

The bug is this:
The waterfall (in panafall) shows about 1-second of high intensity (as if it's noise) color immediately after every TX-to-RX transition.  Other signals still show through it but it's there every time.  There is no actual noise in the receiver or any other effect - only the waterfall.  Three such T->R transitions are shown in the screen capture below.

If I turn off waterfall AGC the effect goes away entirely.  But then I don't get waterfall AGC.

This was not present in the most recent compile of 2.10.2.

![image](https://github.com/ramdor/Thetis/assets/26491401/c6a43cd4-3a42-4784-bdb3-e35286757de4)

**Comment by ramdor** [comment]
2.10.3 is still WIP and as it has not been released there are no release notes. The line is the waterfall auto agc, which has been fixed and as a result causes that line you now see when you move from tx to rx. There is a new option here to delay the waterfall agc by the time needed for the fft bins to fill :

![image](https://github.com/ramdor/Thetis/assets/3124967/d0241b3d-d2e9-41e7-adcf-a59b7e400ead)

I will look at this to see if there is anything I can do before releasing.

**Comment by W2PA** [comment]
Great - thanks.  I know it's not yet released but thought you'd like to know about this effect.  Checking the "Purge" box does indeed solve the problem.

**Comment by W2PA** [comment]
> I think I will pull that option and do it always. The bright band is caused because on T/R I reset the waterfall agc to -200 so it is fully gaining and hence very bright until data starts coming in. I have adjusted it to something more sensible.

Except, as you can see in my screen snip, the data is coming in during the bright flash. So perhaps the max setting was just lasting too long or AGC was delayed in kicking in?

At any rate, I think it's a good idea to eliminate it as an option.  Most users won't understand what it means. And besides, is there a reason for it to be unchecked.  Unchecked only seems to produce this display artifact.  (I'm coming from a standpoint of not knowing that part of the code at all.)

**Comment by ramdor** [comment]
data does come in if the WDSP is not purged. It is the historic data from the bins as they reach levels expected levels for this T or R mox state.

The only reason to have it unchecked would be to reduce cpu cycles if you didn't care too much about visual artifacts.  Either way I have removed the option, and it does it every time now.

**Comment by RdWing** [comment]
Hmm, I appreciate that for some users there is a large artifact. I have always worked around with timing adjustments under Options 1, just a few ms of delay. The new changes, however, seem to cut off the beginning and tail end of the transmission on the waterfall, even though the little burst is still there and being transmitted. We just can't see it now.

It was very comforting knowing that what I saw on the panadapter and waterfall was true to life showing the signal as transmitted...and I'm somehow less comfortable now that it's gone.

Perhaps there is a middle ground that can be achieved? Or can this agc constant be tuned by the user?

I'm also a little concerned because previously you could pretty quickly see if something was being hotswitched, due to it appearing on the panafall, but now it's just dark.

New Version ![Screenshot 2023-11-02 005842](https://github.com/ramdor/Thetis/assets/19214916/fe93cadb-f7e1-4482-b746-eddba8ee013d)
Old Version 
![Screenshot 2023-11-02 010210](https://github.com/ramdor/Thetis/assets/19214916/c34f70a8-86f1-4674-90d9-8a6242d9f420)

I definitely like the old way better.

**Comment by RdWing** [comment]
Hmm, I appreciate that for some users there is a large artifact. I have always worked around with timing adjustments under Options 1, just a few ms of delay. The new changes, however, seem to cut off the beginning and tail end of the transmission on the waterfall, even though the little burst is still there and being transmitted. We just can't see it now.

It was very comforting knowing that what I saw on the panadapter and waterfall was true to life showing the signal as transmitted...and I'm somehow less comfortable now that it's gone.

Perhaps there is a middle ground that can be achieved? Or can this agc constant be tuned by the user?

I'm also a little concerned because previously you could pretty quickly see if something was being hotswitched, due to it appearing on the panafall, but now it's just dark.

New Version (Remote Kiwi receiver on left showing signal as received, Thetis on Right) ![Screenshot 2023-11-02 005842](https://github.com/ramdor/Thetis/assets/19214916/913ef95a-204b-4572-afcb-b8e12960e232)
Old Version 
![Screenshot 2023-11-02 010210](https://github.com/ramdor/Thetis/assets/19214916/3e4e8c41-5e4f-4bbf-bda8-c91131c7b363)

**Comment by ramdor** [comment]
#204 was the original issue reported by Scott. This issue relates to some WIP incorrect waterfall setting. Can you re-post over on #204 ?
