### ISSUE TITLE
 v2.10.3.4 Pre-Release MIDI Control

### ISSUE THREAD

**Issue by pbchristensen** [ramdor/Thetis#270]
**Describe the bug**
No MIDI Control from Hercules DJControl Compact 

**To Reproduce**
Steps to reproduce the behaviour:

As a quick test, I deleted "VFO A" in the list within the "Configure MIDI" dialog box.  I then turned the VFO A wheel and no encoder recognition.  

**Expected behaviour**

MIDI control should be automatically recognized.  

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Windows10 Pro

**Additional context**

N/A

**Comment by ramdor** [comment]
there is a pre-release_2 available as a download which will hopefully fix the issues caused by me just ignoring 14 bit messages. There are a couple of new options on the setup midi form as well, with tooltip info if you need more details. Please give it a go.

https://github.com/ramdor/Thetis/releases/tag/v2.10.3.4-pre-release

**Comment by pbchristensen** [comment]
Richie,

 

Yes, that fixed it.  Thank you!

 

Paul, W9AC

**Comment by NC3Z** [comment]
Fixed the issue with my CMD PL-1 , Thanks

**Comment by W2PA** [comment]
Had no issues with Behringer PL-1 nor Micro.  Both working fine in 2.10.3.4 pre3
