### ISSUE TITLE
UMC Asio Driver disappears 

### ISSUE THREAD

**Issue by DH1KLM** [ramdor/Thetis#317]
Is the procedure in cmASIO Guide.pdf absolutely necessary?

If I follow the instructions and enter the UMC ASIO driver in the registry, Thetis no longer sees my UMC ASIO driver. If I remove the entry , the UMC ASIO driver will be displayed again in Thetis.

**Comment by W4WMT** [comment]
Hi Sigi,
No, the registry procedure is completely optional.  If you don't enter the ASIO driver name in the registry key, then your SDR audio works normally, just as before, no change whatsoever.  However, if you complete the registry entry, the ChannelMaster expects to enjoy exclusive use of the ASIO driver (as specified in the Steinberg ASIO SDK) and VAC will no longer have use of it.  But, again, it is completely optional.
73, Bryan W4WMT

**Comment by DH1KLM** [comment]
Thanks for the clarification. It is not clear in the PDF that it is optional. If the entry is present in the registry, this means that VAC does not have to be switched on (and cannot be switched on), and therefore does not receive any information about under and overflows, ring buffer, latency, etc. Likewise, a tool like Voicemeeter can no longer be used.

Is my assumption correct?

**Comment by W4WMT** [comment]
Hi Sigi,
First, I apologize for the confusion caused by the preliminary guide.  I dashed it together just to get testers a starting place.  I am working on a final version.
VAC will still work just fine, it just won't be able to use the same ASIO device that cmASIO is using.  But you can still use VAC for digital modes, as cmASIO is completely separate from VAC.  The cmASIO is intended to be used with HARDWARE ASIO device drivers, not virtual ASIO drivers like Voicemeeter, ASIO4All, Virtual Audio Cables.  That said, you can try to use Voicemeeter, you may get lucky, but not too likely.  Virtual drivers just can't perform well enough to keep up with the pace set by ChannelMaster.
Yes, all the audio controls will work just as if you were directly connected to your Anan.  cmASIO replaces all the hardware audio streams, TX and RX.  Both receivers will stream to it also, just like the hardware codec in your Anan.
73,
Bryan W4WMT

**Comment by DH1KLM** [comment]
OK, then I'm happy for now. You did a very good job, I think this step was long overdue. Thank you for that.

**Comment by W4WMT** [comment]
Thanks for the comment Sigi.  Just remember, if you don't populate the registry key for ASIOdrivername, then the radio operates just as before - not a single line of code has been changed in that case.

**Comment by W4WMT** [comment]
You may be able to get away with that.  It depends on whether your machine has enough cores and how busy they are trying to do other things at the same time. 
Will you be patching Ableton through Voicemeeter?  If so, there are some steps you need to know about to get VM to play nice with cmASIO.

**Comment by W2PH** [comment]
I am using a RODEcaster DUO as an audio processor/mixer with my 7000 DLE MK II Proto 2 Version 2.10.35 . When I enter RODEcaster in the registry as instructed then load Thetis,  I get a Red icon saying "issue starting cmASIO..... " , yet I can see the RODEcaster ASIO as one of the possible audio drivers listed in VAC 1 choices.  Any suggestions for what might be wrong?  Thanks Ed W2PH

**Comment by DH1KLM** [comment]
Have you tried to run hostsample.exe to identifiy all ASIO drivers installed in your system like it is writen in cmASIO Guide.pdf? 
You can download hostsample.exe from https://github.com/W4WMT/Thetis/releases/tag/v0.0

**Comment by W2PH** [comment]
Yes, that was one of the first things I did.
:-)
