### ISSUE TITLE
EQ[FEATURE]

### ISSUE THREAD

**Issue by syracusepro** [ramdor/Thetis#360]
It will be nice to have the Transmitter Equalizer to have 20 bands instead of 10? Thanks.

**Comment by Aleziss** [comment]
10 band parametric aint enough ? you have the TX EQ plus the CFC, that is a LOT of calibration possibilities...

**Comment by w-u-2-o** [comment]
And don't forget the post-EQ stage as well!

To be clear, the EQ's and CFC are only semi-parametric since there is no
control over filter Q but, still, three stages of 10 band, semi-parametric
spectral tailoring should be more than equal to any possible task.

If you can't get the sound you want, post a message on the Apache forum
asking for advice.

73,

Scott

**Comment by Aleziss** [comment]
True, TX EQ plus the post-EQ with different frequency parameters gives a total of 20 band of semi-parametric like you are saying because we do not have the Q factor adjustment. On my end, I often run eSSB with no CESSB engaged, no leveler engaged with a very smooth CFC curve and tiny adjustments on the pre-EQ and it sounds fantastic. I don't even use the TX EQ as of this moment.

Anyway, it's just to say that Thetis software has a lot of processing for TX.
