### ISSUE TITLE
No TX output when initially going to QSK after band change (related to RF on RX port issue) [BUG]

### ISSUE THREAD

**Issue by W2PA** [ramdor/Thetis#407]
This bug was observed on the new firmware and Thetis combination that fixed the RF on RX port issue (https://github.com/ramdor/Thetis/issues/228).

This bug was observed by/on:
W2PA / ANAN-8000DLE (original)
W1JA / ANAN-7000DLE MkII (with EP4CGX150F896 Cyclone IV).  
 
On the 8000, was running <Metis_Orion_MkII_Protocol_2_v2.2.2.rbf> and Thetis 2.10.3.6 x64 (1/20/24) dev_2.  The symptom is lack of transmitter output on 6m in CW QSK mode upon first changing bands (see below), with a worrisome side-effect.  For all tests, a keyer paddle is connected directly to the radio.
 
Here is how to produce the effect:

0) Bring up Thetis

1) Go to 6m, switch to CWU, choose QSK mode, do NOT transmit
2) Go to any band other than 6m, let's say 10m, switch to CWU, with QSK on
3) Send a couple of dits – notice the transmit power is normal
4) Switch to 6m, make sure it is still in CWU and QSK is on
5) Send some dits - notice you can hear your signal and see a peak on the panadapter, but no output power is indicated on an external meter, or it’s so low that it doesn’t register. Changing the drive slider doesn’t affect it.
6) Switch to SEMI break-in mode, send some dits - notice that normal output power is indicated.
7) Now switch back to QSK mode and send some dits - notice everything is now back to normal and proper output power is indicated.
8) From now on, changing bands does not make the problem recur as long as you stay in QSK mode.  To make it happen again, go to a band other than 6m, send some dits in SEMI break-in, go back to 6m, switch to QSK, send dits and get no output power until you return to step 6.
 
There might be other variations on this theme but the above is repeatable and happens every time on both the 8000 and 7000 MkII.
 
Note 1: The relays sound somewhat louder when the no-output condition in step 5 occurs.  It’s as if additional relays are active.  Maybe this is a clue.
Note 2: W1JA also tried switching to 2.2.1 firmware and the problem did not occur.  Maybe this is an additional clue and indicates the problem is in firmware.
 
Finally, **a worrisome note**:  In the no output mode (step 5) the transmitter seems to be actually trying to operate at full power, but perhaps is not connected to anything.  The evidence for this is that when I send dits in step 5 showing zero on the output meter, my power supply current meter jumps up to a high value – 10s of amps – as if it is transmitting power or trying to.  This may be a dangerous condition for the hardware.

[Edited 19 Feb 24]
Changed the title of this issue to reflect that this is not specific to 6m as originally thought.  See below.

**Comment by laurencebarker** [comment]
What I think is happening here, following some testing last night: The antenna is correctly selected for TX, but the low pass filters used on TX are not. So in the example you list; you TX on 6m but the 10m LPF is still selected. Any other circumstance where you changed to a higher frequency then transmitted will do something similar. 

 

If you change to a lower frequency then transmit, the higher frequency LPF will be selected and will not absorb the TX waveform – but won’t correctly filter harmonics either. 

 

A “quick fix” to prevent damage: after a band change, click TUNE on then off momentarily. That causes the correct filters to be loaded. Or change antenna then change back again.

 

To resolve this: ideally we need Thetis to work out the required TX low pass filter settings on any band change, before a TX has been initiated, and send to the protocol interface code. 

 

The same behaviour happens with G2: the firmware is behaving the same way as orion mk2.

 

I suspect that cross band operation is more complex than we have yet addressed; particularly with orion mk1 and earlier RF hardware that use LPF as part of the RX filtering. 

 

 

Laurence Barker G8NJJ

***@***.***

 

From: Chris Codella ***@***.***> 
Sent: Sunday, February 18, 2024 12:57 PM
To: ramdor/Thetis ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ramdor/Thetis] No 6m output when initially going to QSK (related to RF on RX port issue) [BUG] (Issue #407)

 

This bug was observed on the new firmware and Thetis combination that fixed the RF on RX port issue (#228 <https://github.com/ramdor/Thetis/issues/228> ).

This bug was observed by/on:
W2PA / ANAN-8000DLE (original)
W1JA / ANAN-7000DLE MkII (with EP4CGX150F896 Cyclone IV).

On the 8000, was running <Metis_Orion_MkII_Protocol_2_v2.2.2.rbf> and Thetis 2.10.3.6 x64 (1/20/24) dev_2. The symptom is no transmitter output on 6m in CW QSK mode upon first changing bands (see below), with a worrisome side-effect. For all tests, a keyer paddle is connected directly to the radio.

Here is how to produce the effect:
0) Bring up Thetis

1.	Go to 6m, switch to CWU, choose QSK mode, do NOT transmit
2.	Go to any band other than 6m, let's say 10m, switch to CWU, with QSK on
3.	Send a couple of dits – notice the transmit power is normal
4.	Switch to 6m, make sure it is still in CWU and QSK is on
5.	Send some dits - notice you can hear your signal and see a peak on the panadapter, but no output power is indicated on an external meter, or it’s so low that it doesn’t register. Changing the drive slider doesn’t affect it.
6.	Switch to SEMI break-in mode, send some dits - notice that normal output power is indicated.
7.	Now switch back to QSK mode and send some dits - notice everything is now back to normal and proper output power is indicated.
8.	From now on, changing bands does not make the problem recur as long as you stay in QSK mode. To make it happen again, go to a band other than 6m, send some dits in SEMI break-in, go back to 6m, switch to QSK, send dits and get no output power until you return to step 6.

There might be other variations on this theme but the above is repeatable and happens every time on both the 8000 and 7000 MkII.

Note 1: The relays sound somewhat louder when the no-output condition in step 5 occurs. It’s as if additional relays are active. Maybe this is a clue.
Note 2: W1JA also tried switching to 2.2.1 firmware and the problem did not occur. Maybe this is an additional clue and indicates the problem is in firmware.

Finally, a worrisome note: In the no output mode (step 5) the transmitter seems to be actually trying to operate at full power, but pernaps is not connected to anything. The evidence for this is that when I send dits in step 5 showing zero on the output meter, my power supply current meter jumps up to a high value – 10s of amps – as if it is transmitting power or trying to. This may be a dangerous condition for the hardware.

**Comment by W2PA** [comment]
Thanks for the analysis, Lawrence.  

If I'm understanding correctly, when band changes occur the LP filter choice is not being correctly updated at first, and only under specific circumstances.  I confirmed this by making the same thing happen by starting on 10m, moving up to 40, then back to 10, at which point I again see no output.  There are other weirdnesses but I can't yet discern a pattern.  Cycling MOX once returns things to normal.

So I'm left wondering what changed in the firmware that caused this to occur - or was it a change in Thetis that happened at the same time?  It seems (as above) to change with the particular version of firmware.

**Comment by W2PA** [comment]
Thanks for the additional clarification, Lawrence.  It all makes sense.

73, Chris, W2PA

**Comment by W2PA** [comment]
Finally got around to trying this version (dev_2).  I confirm that the above bug is gone.  Tested on 10/6 and on 40/10 as above.
Thanks!

73, Chris, W2PA
