### ISSUE TITLE
PureSignal SetPK not set correctly on new Thetis installations for G2 [BUG]

### ISSUE THREAD

**Issue by w-u-2-o** [ramdor/Thetis#408]
See: [https://community.apache-labs.com/viewtopic.php?f=48&t=5004](url)

Per Laurence in that thread:

> "Thetis has a parameter SetPk which is important. It is on the linearity form. For a G2 it should be set to  0.6121  and for an Anan7000 it should be set to 0.2899.
> 
> We had modified Thetis to set this for G2 radios; but Warren advised me on Saturday that was no longer being set. It looks like the Thetis code has changed again."

**Comment by ramdor** [comment]
Saturn value of 0.6121 is provided to PSdefpeak(n) function, which updates the data in the PSForm, only if the radio protocol or hardware changes from previous. On a new DB this will obviously update, and  on a radio/protocol change this will update.

The reason for preventing this happening all the time is because an end user may tweak the value and will not want it overwritten. There may be a case for adding additional UI on the PSForm to have a default value with radio button, and user value with radio button to make it obvious what is happening.

Will leave this open for now as a reminder.

**Comment by ramdor** [comment]
closing this, as a none issue atm. Eventually I will re-write the implementation to provide a better ui/config.
