### ISSUE TITLE
Independent database folders for each radio selected 

### ISSUE THREAD

**Issue by Richz28** [ramdor/Thetis#455]
Hi Richie, I have a request, if it's possible could Thetis create, separate database folders for each radio in the list if selected, I use a few different radios and there configured differently,  so if there is any way when selecting a radio you want to use , Thetis will read and write to that specific database folder, examples  (Saturn G2), (Hermes), (7000dle),  names of folders same as radio selected .  Automatically creat these folders in the  c:/users/(PC name ??)/appdata/roaming/openhpsdr. Thanks for all great features you added , Rich Terrusa kc2zur 73

**Comment by oe3ide** [comment]
You can do this by yourself, just use the argument -datapath.
An example cmd would look like:
`c:
cd\
cd "C:\Program Files\openhpsdr\thetis"
start "" "thetis.exe " -autostart -datapath:"%appdata%\OpenHPSDR\Thetis-x64-7000
`

**Comment by Richz28** [comment]
Hi Richie,  I must be honest,  I don't know what to do with this, what and where do I make this edit or entry, will I have a short cut on desktop for each Radio, why can't it be done in this when selecting Radio, that would be great,  but if it's something you don't have time for , sure I understand, your plate is full, but I need a better example how ,where , what , to do with the -database path string above in this email,  thank you Rich Terrusa kc2zur 73

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by oe3ide** [comment]
Ok, here a step-by-step tutorial:
1) Open Notepad (or a Texteditor of your choice - I use notepad++)
2) copy this into the new file (assuming your main-drive is c: and you have installed Thetis in the default location)

c:
cd\
cd "C:\Program Files\openhpsdr\thetis"
start "" "thetis.exe " -autostart -datapath:"%appdata%\OpenHPSDR\Thetis-x64-7000

3) Save the file ie on your desktop as "Thetis-7000.bat"

Your database for the 7000 have to be in here: %appdata%\OpenHPSDR\Thetis-x64-7000, otherwise a new database would be created.

Now you can open Thetis for your 7000 via the icon on the desktop. You can also please these bat-files in another directory (like ie c:\hamradio) and then make a link to your desktop (right-click - send to - desktop)

73 Ernst, OE3IDE

**Comment by Richz28** [comment]
Thank you, Ernest, I'll give it a try , Rich Terrusa kc2zur 73

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Richz28** [comment]
Hi Ernest, thank you,  I used note pad and was able to create the thetis short cut to desk top that made new database name of my choice , and it auto starts too.  Rich Terrusa kc2zur 73

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ramdor** [comment]
this can be achieved with the new database manager in  [v2.10.3.6-rc1](https://github.com/ramdor/Thetis/releases/tag/v2.10.3.6-rc1) Watch the video linked in the change log. Closing.
